### ISSUE TITLE
UI for main search engine window

### ISSUE THREAD

**Issue by DeltaWild** [DeltaWild/Error404_Project3#1]
Main UI for the project.

### Must include:
* Search bar
* Search button
* Selection for AND, OR, PHRASE
* Results window
* Method for maintenance access (button, etc.)

### May include:
* Method to display general program information (e.g. "about" button)
* Indexed files counter
* Program title/name

**Comment by i-own-gamestonk** [comment]
Closed by accident.
But it is done.  Main UI include all of the must includes and may include's.
